Confortalecolchoes leads
f1sales/simmons pull request #3
Opened 2022-02-11 13:52 UTC by thiagoyoussef

2022-02-11 13:59 UTC, thiagoyoussef commented on lib/simmons.rb
> +      def handle_integrated_stores(store_group)
Do you like this method name?

2022-02-11 14:01 UTC, thiagoyoussef commented on lib/simmons.rb
> +      def parse_source(source_name)
I think this method name is not clear.
`parse_source_to_integrated_store` would be more clear but too long.
Do you have any suggestions?

2022-02-14 15:31 UTC, marciok requested changes

2022-02-14 15:31 UTC, marciok commented on lib/simmons.rb
> +      def handle_integrated_stores(store_group)
Try to avoid creating a method with `send_`, ruby already has methods with send where it uses to send messages to object, maybe `forward_` is more correct: 

```ruby
def forward_dreamcomfort
# ...
end

def create_lead_on(store, message)
# ... 
end
```

2022-02-14 15:31 UTC, marciok commented on lib/simmons.rb
> +      def parse_source(source_name)
I think `parse_source` is ok, it's a private method and is parsing a source name

2022-02-14 15:31 UTC, marciok commented on lib/simmons.rb
> +          source_name.split(' - ').map(&:capitalize)[0..1].reverse.join(' - ')
DRY

2022-02-15 20:42 UTC, marciok approved these changes

2022-02-15 20:42 UTC, merged